-- Remove the check constraint that prevents quantity from being less than 1
-- This constraint was likely auto-generated by Hibernate from @Min(1)
ALTER TABLE products DROP CHECK products_chk_1;

-- Optional: Add a new constraint to ensure quantity is non-negative (>= 0)
ALTER TABLE products ADD CONSTRAINT products_qty_non_negative CHECK (quantity >= 0);
